### ISSUE TITLE
Correct Typos in Website Text

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#10]
**Description:** Improve the website's professionalism by fixing any typos or spelling errors in the text content. Contributors can review pages and make corrections.

- Difficulty: Very Easy
- Tags: Proofreading, Text

**Comment by flushthemoney** [comment]
Hey! I would like to solve this issue, kindly assign it to me.

**Comment by Saket009** [comment]
Hey Ishan as I am new to open source I would like to contribute to this. Can you please assign this issue to me ?

**Comment by IshaanAdarsh** [comment]
hi @Saket009 , there are more issues open in the repo. you could look at them.
Or else you can have a similar issue -> #12

**Comment by flushthemoney** [comment]
Hey, I've sent the pull request for this issue. Kindly use the **hacktoberfest-accepted** tag while merging
