### ISSUE TITLE
I want to add footer section in both contact us and register page .

### ISSUE THREAD

**Issue by AkashDev23** [NITRR-Open-Source-Community/NOSC-Website#105]
**Is your feature request related to a problem? Please describe.**
As the footer section should  be in all the pages I want to add that in contact us and register page

**Comment by Aditya9764** [comment]
can i will try to enhance footer added b bhalerao one my the contributer

**Comment by Aditya9764** [comment]
@AkashDev23  
As the footer section should be in all the pages I want to add that in contact us and register page I will provide it by adding <a> tag to footer section please assign this issue to me
