### ISSUE TITLE
Project admis and contributor are out of div and its not responsive 

### ISSUE THREAD

**Issue by techmannih** [NITRR-Open-Source-Community/NOSC-Website#113]
Hello @DaSeeker67 
I found an issue in this website which is not responsible for a small device and mobile phone 
I want to work on this issue...assign me this issue 
![Screenshot_20231015_234036_Chrome](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/125847751/6fc9a27a-1c65-47f5-b2c8-348507d59c4c)

**Comment by DaSeeker67** [comment]
> Hello @DaSeeker67 
> 
> I found an issue in this website which is not responsible for a small device and mobile phone 
> 
> I want to work on this issue...assign me this issue 
> 
> ![Screenshot_20231015_234036_Chrome](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/125847751/6fc9a27a-1c65-47f5-b2c8-348507d59c4c)
> 
> 

Hello @techmannih thanks for letting us know about the bug, can you please clarify at what resolution you are accessing the website and also tell the browser and your device spec so that I can raise a specific issue and assign it to you😄
