### ISSUE TITLE
Hamburger Menu not working in Register Page

### ISSUE THREAD

**Issue by Arnav17Sharma** [NITRR-Open-Source-Community/NOSC-Website#120]
**Description**
The Hamburger navbar menu does not work on the /register page. 

**Difficulty**
Medium

**To Reproduce**
1. Go to 'nosc.netlify.app'.
2. Click on 'Register Now' button.
3. See error while trying to click the burger menu.

**Expected behavior**
Add toggle feature and proper navigation between register page and other pages in the menu. 

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/58596929/f3d37284-c28e-43da-b433-e6c53672a8a1)

**Comment by Nupoor10** [comment]
Hello, Can I work on this?

**Comment by hamzailyas237** [comment]
I want to work om this. Assign it to me

**Comment by Jaimin25** [comment]
If its still not resolved I want to work on this @Arnav17Sharma

**Comment by Jaimin25** [comment]
If its still not resolved I want to work on this @nown1ne @Arnav17Sharma
