### ISSUE TITLE
Add "Privacy Policy" and "Terms of Service" Pages

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#13]
**Description:** Ensure legal compliance, transparency, and address privacy concerns by adding both a "Privacy Policy" and a "Terms of Service" page to the website. Contributors can create basic documents for both pages to provide clear guidelines to users.

- **Difficulty:** Easy

- **Tags:** Privacy, Legal, Terms of Service

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue, can you assign me this? I also want to know the details you want to be added to the "Terms of Service" page of the website.

**Comment by IshaanAdarsh** [comment]
> Hey, I would like to work on this issue, can you assign me this? I also want to know the details you want to be added to the "Terms of Service" page of the website.

There is no real prerequisite for this. You could look are similar projects and how they have created their own terms of service. If you can’t find any similar project, you can create your own TOS. We will help you through it
