### ISSUE TITLE
the words forming a sentence are not visible in the newsletter.

### ISSUE THREAD

**Issue by NandishM0618** [NITRR-Open-Source-Community/NOSC-Website#130]
![bugos](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/100901899/ea617e08-a008-4517-a553-cf062db13d43)

**Comment by Omar-Nabil** [comment]
can you explain the issue more...........do you mean placeholder like this 
![the-difference-placeholder](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/113044700/4191c478-0bf3-4d01-acb7-0ff55236cbc5)
?

**Comment by Omar-Nabil** [comment]
Hey @IshaanAdarsh I'm interested to do work on this, could you please assign me this issue.

**Comment by Omar-Nabil** [comment]
@IshaanAdarsh  i solved this issue https://github.com/NITRR-Open-Source-Community/NOSC-Website/pull/131

**Comment by Omar-Nabil** [comment]
Hey @nown1ne  I'm interested to do work on this, could you please assign me this issue.

**Comment by Soumyajit-Koley** [comment]
Hey @nown1ne could you please assign me this issue..
