### ISSUE TITLE
Create Contributor Section in README.md

### ISSUE THREAD

**Issue by prokaushik** [NITRR-Open-Source-Community/NOSC-Website#14]
Introduce a designated segment in the README.md to recognize and give credit to all individuals who have contributed to the project. This addition aims to nurture a sense of community and express gratitude towards the valuable contributors.

**Comment by IshaanAdarsh** [comment]
> Introduce a designated segment within the About page to recognize and give credit to all individuals who have contributed to the project. This addition aims to nurture a sense of community and express gratitude towards the valuable contributors.

@prokaushik this is kind of like a contributor Section. 
Maybe you can add this in the ReadMe.md for the project, about us part is already covered

**Comment by prokaushik** [comment]
is it acceptable??

**Comment by IshaanAdarsh** [comment]
@prokaushik feel free to create issues you can identify. We appreciate the help

**Comment by prokaushik** [comment]
can you assign me this under hacktoberfest? @IshaanAdarsh

**Comment by nown1ne** [comment]
@prokaushik we already have a contributor section in the readme file, so I'll be closing this issue 
You can propose your idea for creating a contributor section in website by creating a new feature request issue. Check the readme file for an example implementation.
