### ISSUE TITLE
Privacy & policy page not maintained properly

### ISSUE THREAD

**Issue by Shivam250702** [NITRR-Open-Source-Community/NOSC-Website#150]
**Is your feature request related to a problem? Please describe.**
The css and styling is not properly maintained
**Describe the solution you'd like**
I would make the styling more precise and up to the mark
**Describe alternatives you've considered**

**Additional context**

**Comment by IshaanAdarsh** [comment]
@Shivam250702 would you like to work on it

**Comment by Shivam250702** [comment]
Yeah please assign it to me
