### ISSUE TITLE
Alignment not proper for Project Maintenence & Admins and Project Contributors

### ISSUE THREAD

**Issue by hemantgovekar** [NITRR-Open-Source-Community/NOSC-Website#153]
**Description**
Alignment not proper for Project Maintenence & Admins and Project Contributors

**Difficulty**
Low

**To Reproduce**
1. Go to 'nosc.netlify.app'
2. Scroll down to 'Project Maintainers & Admins and Project Contributors ' section
4. You can see the above section are misaligned to the main page ( Screenshot attached)

**Expected behavior**
Alignment should be proper

**Screenshots**

@
![Alignment issue](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/19679797/1abaea10-ebc8-46fc-a19a-1279128cddd4)

**Desktop (please complete the following information):**
 - OS : Windows 10 
 - Browser : Chrome 
 - Version : 120.0.6099.129 (Official Build) (64-bit)

**Comment by hemantgovekar** [comment]
I can work on this issue, let me know if thats ok.

**Comment by hemantgovekar** [comment]
@IshaanAdarsh : hello Ishaan, did you get a chance to look at the issue ?

**Comment by IshaanAdarsh** [comment]
@hemantgovekar I have assigned the issue. I will review the PR asap

**Comment by hemantgovekar** [comment]
@IshaanAdarsh  : DONE
