### ISSUE TITLE
Fix logo in navbar

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#2]
**Description**
The logo of NOSC in the navbar of the homepage is compressed and not visible properly.

**Difficulty**
Medium

**To Reproduce**
1. Go to 'nosc.netlify.app'
3. Notice the nosc logo in the navbar

**Expected behavior**
The logo should be clearly visible also add a hover effect to emphasize 

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/134809b4-5557-441e-b54b-dc6aeea2229a)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Edge
 - Version 117

**Additional context**
none

**Comment by yashi-15** [comment]
I can fix this issue. Please assign it to me.

**Comment by bhalerao-2002** [comment]
Hello @IshaanAdarsh,
I want to say that even if you fix the logo size. The background will degrade your brand name.
it will hurt your repository's reputation.
I am experienced in this, Assign me this I will work on, all the designing.

**Comment by nown1ne** [comment]
We acknowledge and greatly value your dedication. Please don't hesitate to open a new issue where you can elaborate on your proposed actions and the specifics of your plan. To facilitate smoother progress tracking, kindly break down the issue into manageable chunks.
