### ISSUE TITLE
Link the privacy policy page

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#23]
**Description**
Link the privacy policy page to the 'link' link of the navbar and footer

**Difficulty**
easy

**Expected behavior**
The 'link' text should be changed to privacy policy and should direct to the privacy policy page

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/c6c1e591-b636-4582-a6cb-03a629edb8a0)
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/e04a9191-b496-4c69-b2de-aa4a0d0c91f7)

**Comment by khushpreetsinghb** [comment]
I am new to open source, I can do this can you please assign this to me.
