### ISSUE TITLE
Fix the hamburger menu

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#25]
**Description**
The hamburger menu is not functional and does close once opened

**Difficulty**
Medium-Hard

**To Reproduce**
1. Go to 'nosc.netlify.app'
2. Click on the hamburger menu
3. See error

**Expected behavior**
The hamburger menu should open and close properly 

**Screenshots**
![WhatsApp Image 2023-10-01 at 10 26 35 AM](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/032c9f2a-bab1-4e64-8ce1-d284c58dbc31)

**Desktop (please complete the following information):**
 - OS: Android 13
 - Browser Chrome

**Comment by Arnav17Sharma** [comment]
Hey, can you assign this to me?

**Comment by ayushman075** [comment]
Sir I want to solve this issue pls assign this to me
