### ISSUE TITLE
Add Event Listings

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#27]
**Description:** Currently, the events page is empty. Let's add a section on the events page to list upcoming events. This will provide visitors with a quick overview of what's coming up.

- **Task:** Create a section on the events page with a clear layout for event listings.
- **Additional Info:** Include event titles, dates, brief descriptions, and links for more details.
- **Labels:** Enhancement, Events

**Comment by DaSeeker67** [comment]
I will be adding this feature

**Comment by DaSeeker67** [comment]
Do we need to add some random upcoming events?

**Comment by IshaanAdarsh** [comment]
make placeholders for the events, about 6. try making a horizontal slide. This will take up a lot of space.
