### ISSUE TITLE
Event Notification

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#32]
**Description:** Implement a notification system to keep users informed about upcoming events. This could be through email notifications or pop-up messages on the website.
- **Task:** Set up a notification system that sends reminders for upcoming events.
- **Additional Info:** Users should have the option to subscribe or unsubscribe from event notifications.
- **Labels:** Enhancement, Events

**Comment by probot-codes** [comment]
Sir, may I be assigned this issue please?

**Comment by DaSeeker67** [comment]
I can try with popup notifications

**Comment by Ronakkk07** [comment]
Hello Sir, I have already started working on this issue. is it compulsory to get the issues assigned?

**Comment by IshaanAdarsh** [comment]
> Hello Sir, I have already started working on this issue. is it compulsory to get the issues assigned?

Yes @Ronakkk07, you can suggest your own way. But we will go with the better implementation at the end. It makes it safe if you are assigned the issue. 

If you want to have a sure issue, then look at other issues in this repo. If all are assigned the you can see the issues of 

https://github.com/IshaanAdarsh/ezmail
