### ISSUE TITLE
Event Feedback Form

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#33]
**Description:** After attending events, it's valuable to collect feedback from attendees. Let's create a feedback form for this purpose.
- **Task:** Design a feedback form with questions related to the event experience.
- **Additional Info:** Ensure that the form is easily accessible after events.
- **Labels:** Enhancement, Events

**Comment by Baburao-sanivada** [comment]
Can I know where the form should be placed and what are the questions to be Added?

**Comment by IshaanAdarsh** [comment]
The forms should be near the footer ideally.

**Comment by mhsh312** [comment]
I want to solve this issue. Kindly assign it to me.

**Comment by mhsh312** [comment]
Ok I have the codebase setup and I understand the issue. But can you give more detail as to where in the website do you want the form(at which page)? And are there any specific fields you want in the form?

**Comment by DaSeeker67** [comment]
I want to contribute to this issue

**Comment by dipteshrastogi** [comment]
Sir, may I be assigned this issue please?

**Comment by DaSeeker67** [comment]
Sir, Assign it to me i can do it

**Comment by DaSeeker67** [comment]
Sir check if form is designed correctly, one more thing if you need to save the form either we have to add express or php ![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/65525769/57b37261-eb26-441b-9468-31c56318986c)

**Comment by nown1ne** [comment]
The form looks good 
We will need to discuss how we will be handling the form data feel free to suggest implementation ideas

**Comment by DaSeeker67** [comment]
I believe php or flask will be easy for implementing, but you have to create the server and then only i can create the method to fetch data from formmand store , other wise we can try to implement node and express, whichever way you prefer

**Comment by IshaanAdarsh** [comment]
@DaSeeker67 using php is a good idea, but not a lot of people will be comfortable with using php. I would say try node and express

**Comment by DaSeeker67** [comment]
Ok sure sir

**Comment by DaSeeker67** [comment]
SIR, CAN I PUSH THE FORM IN THIS PR AND YOU CAN MAKE ISSUE FOR THE KICKSTATING OUR BACKEND USING NODEJS AND EXPRESS AND ASSIGN IT TO ME AND I WILL DO IT,  AS LOT OF THINGS NEED TO INSTALLED IN THIS UPDATE AND ALSO I WILL MAKE THE FORM SUBMISSION FUNCTIONAL

**Comment by nown1ne** [comment]
Ok sounds good to me
Create a new issue and explain your solution there and you can start working on it after we finalise

**Comment by DaSeeker67** [comment]
Ok sir, So i can push this code for now and will make issue for the backend soon
