### ISSUE TITLE
Images not showing in the "Know Our Team" section of the homepage

### ISSUE THREAD

**Issue by mhsh312** [NITRR-Open-Source-Community/NOSC-Website#39]
**Description**
The "Know our Team" section in the home page only shows the picture of Abhinav Srinivas and no one else.

**Difficulty**
Easy

**To Reproduce**
1. Go to the home page of https://nosc.netlify.app/
2. Click on 'Know our Team' 
3. Notice the images in the cards.

**Expected behavior**
All the images should be visible

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/135870090/ea85e21e-42d8-44e4-a3fb-da08549f0320)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge (chromium version)
 - Version 117.0.2045.43 (Official build) (64-bit)

**Additional context**
The source link for these images are not working when opened in the browser. That seems to be the issue. New links to be provided for the fix.

**Comment by mhsh312** [comment]
Can you provide me new links or pictures of the team so I can add them?

**Comment by mhsh312** [comment]
@nown1ne please provide me the images so i can fix this issue asap

**Comment by Rohit-Sharmaa** [comment]
@mhsh312  are you working on this issue ?
if not please assign this issue to me ??

**Comment by nown1ne** [comment]
Apologies, but this matter seems to have unintentionally passed our attention.
Here are the linkedin profiles

https://www.linkedin.com/in/ishaan-adarsh-161a56222/
https://www.linkedin.com/in/kraniket901
https://www.linkedin.com/in/anurag-deo-03410a229/
