### ISSUE TITLE
Identify and Fix Broken Links

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#4]
**Description**
Ensure a seamless user experience by identifying and fixing any broken links on the website. Review the site's links and update or remove any links that no longer work.

**Difficulty**
Easy

**Comment by sarafurd** [comment]
Please assign this to me

**Comment by yashwanthvarma18** [comment]
Hello @nown1ne , I'm eager to contribute. Please assign me

**Comment by yashwanthvarma18** [comment]
Could you kindly clarify which types of links should be addressed in this task? For instance, should I focus on repairing links to external websites, social media profiles (such as Instagram, Twitter, LinkedIn), or any additional specific categories of links? or should solely be on correcting the existing broken links within the content, or if I should also consider adding new links.

**Comment by nown1ne** [comment]
Links in the navbar are broken work on fixing them first
If you find others that can be worked on create an issue detailing the problem and your solution

**Comment by yashwanthvarma18** [comment]
Can I send a pull request on October 1st to have it counted in Hacktoberfest?

**Comment by yashwanthvarma18** [comment]
Hey, what does the 'link' section relate to on the website?

**Comment by yashwanthvarma18** [comment]
Is it correct that the 'achievements' navigation item is directing to the 'events' section?

**Comment by nown1ne** [comment]
Links section is currently only a placeholder we are planning to add the privacy policy page there, but it is currently not finalised yet.
No, change the achievements link text to events.

**Comment by yashwanthvarma18** [comment]
Okay ,i initialised a sliding animation for about our team  section

**Comment by yashwanthvarma18** [comment]
hello @nown1ne can you check the pull request i sent you and merge it
