### ISSUE TITLE
Webpage padding issue causes horizontal overflow

### ISSUE THREAD

**Issue by ashmitsinghk** [NITRR-Open-Source-Community/NOSC-Website#42]
**Description**
The webpage has irregular padding conflicts which makes a horizontal scrollbar appear and the body leaks out to the right side of the viewport.

**Difficulty**
Beginner-friendly

**To Reproduce**
1. Go to website
2. See error

**Expected behavior**
The content shouldn't overflow horizontally from the viewport and the user should not be able to scroll to the right.

**Screenshots**
![Screenshot 2023-10-01 123216](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/58002155/a7e1caac-0f1d-4e0e-aaf4-9319f0fa4035)

**Desktop:**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version: 118.0.1 (64-bit)

**Comment by ashmitsinghk** [comment]
I would like to work on it to fix this issue, kindly assign this issue to me.

**Comment by nown1ne** [comment]
Great work finding this issue @ashmitsinghk 
This does not appear to be an issue on MacOs
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/4d1fcc79-d0f7-4b4a-a348-5b88e32c7570)
