### ISSUE TITLE
Link not visible

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#5]
**Description**
When howevered on the links in the navbar are not visible

**Difficulty**
Medium

**To Reproduce**
1. Go to 'nosc.netlify.app'
2. Hover over any link in the navbar to observe the limited visibility

**Expected behavior**
The link text should be visible when the link is hovered upon

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/b747d4d1-bf9b-4262-95a0-3d95a9415dd9)

**Desktop (please complete the following information):**
 - OS: MacOs
 -  Browser Edge
 - Version 117

**Additional context**
Nil

**Comment by yashi-15** [comment]
I can fix this issue. Please assign it to me..
