### ISSUE TITLE
Hamburger not functional in contact us

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#50]
**Description**
Hamburger menu not functional in the contact us page

**Difficulty**
medium

**To Reproduce**
1. Go to 'nosc.netlify.app/contact'
2. Click on hamburger
3. Notice that it is not functional

**Expected behavior**
The hamburger should open and close properly

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/50e53261-d1cb-4fce-ad93-6ca2a2c196db)

**Comment by Arnav17Sharma** [comment]
Can you assign this to me?
