### ISSUE TITLE
Fix know our team link in footer

### ISSUE THREAD

**Issue by khushpreetsinghb** [NITRR-Open-Source-Community/NOSC-Website#51]
**Description**
The Know Our Team link in footer just reloads the page and not scroll to that section.

**Difficulty**
Easy

**To Reproduce**
1. Go to footer of the website
2. Click on Know Our Team link
3. It just reloads the page

**Expected behavior**
It should scroll to that particular section of the website (Team Section) as the link in the navbar does.

**Screenshots**
![Screenshot (35)](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/115068621/921b8dff-3e5f-4504-a50b-934d1ed9cd61)
The link Know Our Team (shown above) should scroll to this section of the website.
![Screenshot (36)](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/115068621/a6231bb2-ff52-44b0-8c17-dcc2a27548a2)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 8]
 - Browser [e.g. chrome]
 - Version [e.g. 109]

**Additional context**
none

**Comment by ayushman075** [comment]
I want to solve this isssue

**Comment by nown1ne** [comment]
The issue creators are auto assigned if they interested in solving the issue 
otherwise they can choose who to assign 
so ask @khushpreetsinghb

**Comment by khushpreetsinghb** [comment]
Yes, I want to solve this.

**Comment by khushpreetsinghb** [comment]
I have already fixed this and sent the pull request. If you want to work on this issue, you should tell someone to assign it to you.
