### ISSUE TITLE
Hamburger not functional in Events page

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#52]
**Description**
Hamburger menu nofunctional in the contact us page

**Difficulty**
medium

**To Reproduce**

1.Go to 'nosc.netlify.app/achivements'
2.Click on hamburger
3.Notice that it is not functional

**Expected behavior**
The hamburger should open and close properly

**Screenshots**
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/577c98a6-39cf-418f-bb11-f0e739e018f6)

**Comment by Akshay9607** [comment]
can i work on this ?

**Comment by DaSeeker67** [comment]
Hamburger not visible ![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/65525769/f2e4032d-770f-422e-a3c5-6ed28c1a8c73)

**Comment by DaSeeker67** [comment]
I can resolve this

**Comment by AviralPatel0526** [comment]
i want to do this
