### ISSUE TITLE
Events page has wrong url

### ISSUE THREAD

**Issue by nown1ne** [NITRR-Open-Source-Community/NOSC-Website#53]
**Description**
The event page has the url achivements

**Difficulty**
easy

**To Reproduce**
1. Go to 'nosc.netlify.app/achievements'
2. Notice that the page is actually about events

**Expected behavior**
the url should be events

**Screenshots**

![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/25835195/477270c2-41ce-4075-a925-95e97502e869)

**Comment by Snowfall22** [comment]
interested
