### ISSUE TITLE
Fixing Navbar.

### ISSUE THREAD

**Issue by yashi-15** [NITRR-Open-Source-Community/NOSC-Website#63]
There is a bit uncomfortable styling in the navbar. There are some changes I would like to make:

- Make the nav bar wider.
- Making the navbar sticky.
- Increase the top-padding in the navbar.
- There should be a little more space between the links.

Please assign this issue to me under Hacktoberfest.

**Comment by nown1ne** [comment]
please provide a mockup image so that we can evaluate it better

**Comment by Smit1610** [comment]
@yashi-15 Can you please assign to me.
