### ISSUE TITLE
[Bug]:Update the logo of the twitter.

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [NITRR-Open-Source-Community/NOSC-Website#68]
**Description**
The logo of the twitter is chaged to 'X' so you should change the logo to the updated logo of the twitter

**Difficulty**
Easy

**To Reproduce**
1. Go to '.Website..'
2. Scroll down to '.website...'
4. See error the twitter logo

**Expected behavior**
The twitter logo should be changed to the updated logo

**Screenshots**

<img width="929" alt="Screenshot 2023-10-02 121901" src="https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/130988755/90eca841-ca71-404b-ab94-a8d6de6078f4">

**Comment by Rohit-Sharmaa** [comment]
@nown1ne  I am interested in this issue Please assign this issue .

**Comment by AviralPatel0526** [comment]
I want to work on this issue

**Comment by Rohit-Sharmaa** [comment]
@nown1ne I am working on this issue . So please don't merge the pr
