### ISSUE TITLE
Improve Footer section

### ISSUE THREAD

**Issue by bhalerao-2002** [NITRR-Open-Source-Community/NOSC-Website#7]
**Description**
The footer Section of the website is not attractive, Improvement is needed in the **Useful links, About us and social handles.**  Icons are repeated, New subscription form needs to be created.
![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/96150629/016b20b0-388a-42f8-bdc8-0ffa87d16c1d)

**Comment by bhalerao-2002** [comment]
Hi @nown1ne and @IshaanAdarsh ,
I raised Problems, If you think it should be fixed, I can help.
Assign me this under Hacktoberfest 2023.

Note: Add "Hacktoberfest" and "Hacktoberfest-Accepted" before assigning.

**Comment by nown1ne** [comment]
Good Work @bhalerao-2002 !!
You can start working

**Comment by bhalerao-2002** [comment]
Hello @nown1ne , @IshaanAdarsh , 
I had done my work. Please check and review it.

Note: Use the "Hacktoberfest-accepted" tag for merging, If my efforts were satisfactory :)
