### ISSUE TITLE
Update Link to the Event Page on the Privacy Policy Page

### ISSUE THREAD

**Issue by probot-codes** [NITRR-Open-Source-Community/NOSC-Website#79]
**Description**
The Link to the Events Page is not working on the Privacy Policy Page. Please fix this issue.

**Difficulty**
Easy

**To Reproduce**
1. Go to 'nosc.netlify.app'
2. Go to the Privacy Policy page.
3. Click on the Events button on the Navbar.

**Expected behavior**
The link should redirect you to the Events page.

**Screenshots**
If you go the Privacy policy page and then click on the events page.
<img width="960" alt="image" src="https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/134484422/9b65a778-6f97-4c94-82cb-1f1b36b20255">

It shows an error.

<img width="639" alt="image" src="https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/134484422/8114bd8b-8085-44f0-a96a-c6b5aa4b8a7c">

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by pnnv** [comment]
Can I have this one?
