### ISSUE TITLE
Add Contributors Section

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#9]
**Description**: Consider adding a dedicated section in the about page to acknowledge and credit all contributors to the project. This can foster a sense of community and appreciation among contributors.
- Difficulty: Medium
- Tags: Community, Contributors

**Comment by prokaushik** [comment]
I am capable of handling this effectively. Kindly assign me this issue. @IshaanAdarsh

**Comment by IshaanAdarsh** [comment]
Hello @prokaushik,
Start working on  #12. If you can complete this I will assign you the other tasks as well. We can't hold up tasks by assigning them to a singular person.

**Comment by prokaushik** [comment]
okay @IshaanAdarsh Thank you for entrusting me with Task #12. I'll also explore the projects listed on https://github.com/IshaanAdarsh/ezmail/issues.
If you have any specific guidelines or preferences regarding Task #12 or if there are particular aspects of the other projects you'd like me to focus on, please feel free to share them. I'm here to ensure a smooth and collaborative workflow.

**Comment by harishghasolia07** [comment]
Can I also Work on it @IshaanAdarsh

**Comment by IshaanAdarsh** [comment]
@harishghasolia07 I will try to have a look at it ASAP. @nown1ne if you are free can you look at it

**Comment by harishghasolia07** [comment]
Do you want some card appearance changes like when you hover on the card then card like flip or something else?
@nown1ne @IshaanAdarsh

**Comment by nown1ne** [comment]
You can detail your idea in a new issue and we can discuss there. Add images so that we can get a clear idea
